import java.util.*;

public class Bfs extends Search{
	
	Position A;
	Position B;
	Position C;
	Position agent;
	
	public Bfs(int[][] initState, int[][] goalState, int N, Position A, Position B, Position C, Position agent) {
		super(initState, goalState, N);
		this.A = A;
		this.B = B;
		this.C = C;
		
		this.agent = agent;
	}
	
	public void bfs() {
		Grid startNode = new Grid(initState, A, B, C, agent);
		
		if(startNode.checkGoalState()) {
			System.out.println("found goal state");
			startNode.printState();
			return;
		}
		Queue<Grid> frontier = new LinkedList<Grid>();
		frontier.add(startNode);
		
		while(!frontier.isEmpty()) {
			Grid currentNode = frontier.poll();
			
			// Here the current node expands.
			Search.RUNNING_TIME ++;
			currentNode.nodesGeneratedBefore = Search.RUNNING_TIME;
			
			for(Grid neighbor : currentNode.getNeighbors(currentNode)) {
				if(neighbor.checkGoalState()) {
					retracePath(neighbor);
					return;
				}
				frontier.add(neighbor);
			}
			
		}
	}
	
	private void retracePath(Grid node) {
		Grid currentNode = node;
		
		List<Grid> path = new ArrayList<>();
		while(currentNode != null) {
			path.add(currentNode);
			currentNode = currentNode.parent;
		}
		
		Collections.reverse(path);
		
		for(Grid g : path) {
			g.printState();
			System.out.println("Number of nodes generated by now " + g.nodesGeneratedBefore);
			System.out.println();
			
		}
		
	}

}
